config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :events do
    resources :comments, :controller => 'event_comments'
  end

  namespace :admin do
    resources :events
  end

   root 'events#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :event_categoryships
  has_many :events, :through => :event_categoryships
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :reply
  belongs_to :user
  belongs_to :event

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates_presence_of :topic

  belongs_to :user

  has_many :event_categoryships
  has_many :categories, :through => :event_categoryships

  has_many :comments, :dependent => :destroy
end

app/models/event_categoryship.rb
class EventCategoryship < ActiveRecord::Base

  belongs_to :event
  belongs_to :category

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  ROLE_ADMIN = 'admin'

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :events

  def short_name
    self.email.split("@").first
  end

  def admin?
    self.role == ROLE_ADMIN
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :first_name
      devise_parameter_sanitizer.for(:sign_up) << :last_name
      
      devise_parameter_sanitizer.for(:account_update) << :first_name
      devise_parameter_sanitizer.for(:account_update) << :last_name
  end

end

app/controllers/event_comments_controller.rb
class EventCommentsController < ApplicationController

  before_action :set_event

  def index
    @comment = Comments.new
    @comments = @event.comments
  end


  def create
    @comment = @event.comments.build(comment_params)
    @comment.user = current_user
    @comment.save

    redirect_to event_path(@event)
  end

  def destroy
    @comment = @event.comments.find(params[:id])
    @comment.destroy
    redirect_to event_path(@event)
  end

private

  def comment_params
    params.require(:comment).permit(:reply)
  end

  def set_event
    @event = Event.find(params[:event_id])
    
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!, :except => [:index]

  before_action :set_event, :only => [ :show, :edit, :update, :destroy ]


  def index
    @events = Event.page(params[:page]).per(5)
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.new(event_params)
      if @event.save
      redirect_to :action => :index
      flash[:notice] = "訊息已成功發佈"
    else
      render :action => :new
    end
  end

  def show
    @page_title = @event.topic
    @comments = @event.comments
    @comment = Comment.new
  end

  def update
    if @event.update(event_params)
      redirect_to :action => :show, :id => @event
      flash[:notice] = "訊息已成功更新"
    else
      render :action => :edit 
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
    flash[:alert] = "訊息已成功刪除"
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:topic, :content,:event_id, :category_ids => [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_comments_helper.rb
module EventCommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>

<div class="form_group">
<%= f.label :topic, "Topic" %>
<%= f.text_field :topic , :class => "form-control" %>
</div>

<div class="form_group">
<%= f.label :content, "Content" %>
<%= f.text_area :content , :class => "form-control" %>
</div>

app/views/events/edit.html.erb
<%= form_for @event, :url => event_path(@event) do |f| %>
<hr>
<%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>

   <%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Update" %>
<% end %>
<p><%= link_to 'Cancel', events_path %></p>

app/views/events/index.html.erb
<h1>災情訊息中心</h1>

<table class="table">
  <tr>
    <td>標題</td>
    <td>發佈者</td>
    <td>發佈時間</td>
    <td>操作</td>
  </tr>
  <% @events.each do |e| %>
    <tr>
      <td><%= link_to "#{e.topic}", event_path(e) %></td>
      <td><%= e.user.short_name %></td>
      <td><%= e.updated_at %></td> 
      <td><%= link_to "細節", event_path(e), :class => "btn btn-primary" %>
      <%= link_to "編輯", edit_event_path(e) , :class => "btn btn-default"%>
      <%= link_to "刪除", event_path(e), :method => :delete, :data => { :confirm => "Are you sure?" }, :class => "btn btn-danger" %></td>
    </tr>
  <% end %>  
</table>
  
  <hr>

<p><%= paginate @events %></p>

<p><%= link_to "新增訊息", new_event_path, :class => "btn btn-primary" %></p>

app/views/events/new.html.erb
<%= form_for @event, :url => events_path do |f| %>
<hr>
<%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>

<%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Create" %>
<% end %>
<p><%= link_to 'Cancel', events_path %></p>

app/views/events/show.html.erb
<h1><%= @event.topic %></h1>
<h3>類別：</h3><p><% @event.categories.each do |c|%> 
  <%= c.name %>
  <% end %></p>

  <table class="table">
<tr>
  <td rowspan="2">
    詳細內容：<%= simple_format(@event.content) %>
  </td>
  
  <td>Published by <%= @event.user.short_name %>
  </td>
</tr>
<tr>


  <td>
    Published at <%= @event.updated_at %>
  </td>
</tr>
  </table> 
  
<p>Comments here:</p>


<table class="table">
  <% @comments.each do |cm| %>
<tr>
  <td rowspan="2"><%= cm.reply %></td>
  
  <td>by <%= cm.user.short_name%> on <%=cm.updated_at%></td>
</tr>
<tr>
  

  <td>
  <%= link_to '刪除', event_comment_path(@event, cm), :method => :delete %>
  </td>
</tr>
  <% end %>
</table>


<%= form_for @comment, :url => event_comments_path(@event) do |f| %>


<%= f.label :reply, "回覆" %>
<%= f.text_area :reply %>

    <%= f.submit "送出" %>
<% end %>


<p><%= link_to 'Back to index', events_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "MidTerm" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<div class="container">
  <div class="row">
    <div class="col-md-12">

      <% if flash[:notice].present? %>
        <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
      <%end%>

      <% if flash[:alert].present? %>
        <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
      <%end%>

        <% if current_user %>

        Hi, <%= current_user.email %>

        <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
        <%= link_to('修改密碼', edit_registration_path(:user)) %>
      <% else %>
        <%= link_to('註冊', new_registration_path(:user)) %> |
        <%= link_to('登入', new_session_path(:user)) %>
      <% end %>
      
<%= yield %>
    </div>
  </div>
</div>

</body>
</html>